namespace Provisio.Services;

/// <summary>
/// Minimal in-app localization. Strings live in per-language tables keyed by a
/// dotted id; English is the master table and the fallback for missing entries.
/// Adding a language = adding one dictionary below and one entry in Languages.
/// </summary>
public static class Loc
{
    public record Language(string Code, string DisplayName);

    public static IReadOnlyList<Language> Languages { get; } = new[]
    {
        new Language("en", "English"),
        new Language("de", "Deutsch"),
        new Language("es", "Español"),
        new Language("fr", "Français")
    };

    public static event EventHandler? LanguageChanged;

    private static string _current = "en";

    public static string Current => _current;

    /// <summary>Pick the app language, falling back to English for unknown codes.</summary>
    public static void SetLanguage(string code, bool notify = true)
    {
        code = (code ?? "").Trim().ToLowerInvariant();
        if (code.Length > 2) code = code[..2];
        if (!Tables.ContainsKey(code)) code = "en";
        if (code == _current) return;
        _current = code;
        if (notify) LanguageChanged?.Invoke(null, EventArgs.Empty);
    }

    /// <summary>Best guess from the OS UI language — used the very first time the app runs.</summary>
    public static string SystemLanguage()
    {
        try
        {
            var code = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToLowerInvariant();
            return Tables.ContainsKey(code) ? code : "en";
        }
        catch { return "en"; }
    }

    public static string T(string key)
    {
        if (Tables.TryGetValue(_current, out var table) && table.TryGetValue(key, out var value)) return value;
        if (Tables["en"].TryGetValue(key, out var english)) return english;
        return key;
    }

    public static string T(string key, params object[] args)
    {
        try { return string.Format(T(key), args); }
        catch { return T(key); }
    }

    private static readonly Dictionary<string, Dictionary<string, string>> Tables = new()
    {
        ["en"] = En,
        ["de"] = De,
        ["es"] = Es,
        ["fr"] = Fr
    };

    // ---------------------------------------------------------------- English

    private static Dictionary<string, string> En => new()
    {
        ["nav.kits"] = "Kits",
        ["nav.recommend"] = "Recommended",
        ["nav.search"] = "Search",
        ["nav.profiles"] = "Profiles",
        ["nav.editor"] = "Kit Editor",
        ["nav.updates"] = "Updates",
        ["nav.settings"] = "Settings",

        ["common.back"] = "Back",
        ["common.next"] = "Next",
        ["common.skip"] = "Skip this step",
        ["common.cancel"] = "Cancel",
        ["common.close"] = "Close",
        ["common.ok"] = "OK",
        ["common.save"] = "Save",
        ["common.delete"] = "Delete",
        ["common.import"] = "Import",
        ["common.export"] = "Export",
        ["common.duplicate"] = "Duplicate",
        ["common.done"] = "Done",
        ["common.retry"] = "Retry failed",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.continue"] = "Continue",
        ["common.refresh"] = "Refresh",
        ["common.selectall"] = "Select all",
        ["common.clear"] = "Clear",
        ["common.updating"] = "Updating…",
        ["common.failed"] = "Failed",
        ["status.queued"] = "Queued",
        ["status.downloading"] = "Downloading…",
        ["status.installing"] = "Installing…",
        ["status.skipped"] = "Skipped",

        ["update.available"] = "Provisio {0} is available (you have {1}). {2}",
        ["update.download"] = "Download",

        ["welcome.title"] = "Welcome to Provisio",
        ["welcome.body"] = "Thank you for downloading Provisio! This is a first-run setup wizard for Windows: pick the kits you want, answer a few questions, review everything, and Provisio installs it all in one batch.\n\nNothing is ever installed until you confirm it on the review screen.",
        ["welcome.hint"] = "Tip: not sure where to start? Try Recommended — a short questionnaire that builds a setup for you.",
        ["welcome.start"] = "Browse kits",
        ["welcome.recommend"] = "Start Recommended Setup",

        ["security.title"] = "Before you import a community kit",
        ["security.body"] = "Kits are not just lists of apps: they can run shell commands, PowerShell scripts and downloaded installers with your account — and, if the kit asks for it, as administrator.\n\nOnly import kits from a source you trust. Open the kit in the Kit Editor first and read every action (winget id, download URL, shell or script body) before you install anything from it.",
        ["security.ack"] = "I understand, continue",
        ["security.info"] = "This warning is shown once. Imported kits are always shown in the Kit Editor before anything runs.",

        ["kits.title"] = "Welcome to Provisio",
        ["kits.subtitle"] = "Pick the kits you want to set up. Nothing is installed until you review and confirm at the end.",
        ["kits.review"] = "Review selections",
        ["kits.start"] = "Start setup",
        ["kits.none"] = "No kits selected",
        ["kits.count"] = "{0} kits selected",
        ["kits.count.one"] = "1 kit selected",
        ["kits.nonetitle"] = "No kits selected",
        ["kits.nonebody"] = "Select at least one kit to start the setup wizard.",

        ["wizard.kitof"] = "Kit {0} of {1} — {2}",
        ["wizard.step"] = "Step {0} of {1}",
        ["wizard.review"] = "Review",
        ["wizard.nextkit"] = "Next kit",

        ["summary.title"] = "Review your setup",
        ["summary.subtitle"] = "Everything queued so far. Uncheck anything you don't want — nothing has been installed yet.",
        ["summary.saveprofile"] = "Save as profile",
        ["summary.preview"] = "Preview commands",
        ["summary.install"] = "Install",
        ["summary.empty"] = "Nothing queued yet. Go back and pick some software or tweaks.",
        ["summary.previewtitle"] = "Dry run — exact commands that will run",
        ["summary.nothingqueued"] = "Nothing queued.",
        ["summary.profiletitle"] = "Save selection as profile",
        ["summary.profilename"] = "Profile name",

        ["install.title"] = "Installing",
        ["install.ready"] = "Ready. Installation runs one item at a time; failures won't stop the rest.",
        ["install.nothing"] = "Nothing queued.",
        ["install.admin"] = "Some actions need administrator rights. Restart Provisio as administrator to run them.",
        ["install.restartadmin"] = "Restart as administrator",
        ["install.exportlog"] = "Export log",
        ["install.start"] = "Start installation",
        ["install.restore.on"] = "Restore point: on",
        ["install.restore.off"] = "Restore point: off",
        ["install.creatingrestore"] = "Creating restore point…",
        ["install.running"] = "Installing {0}…",
        ["install.alldone"] = "All done.",
        ["install.failed"] = "Finished with {0} failure(s). You can retry the failed items.",

        ["search.title"] = "Search everything",
        ["search.placeholder"] = "Find apps and tweaks across all kits…",
        ["search.queue"] = "Queue",
        ["search.queued"] = "Queued",

        ["profiles.title"] = "Profiles",
        ["profiles.subtitle"] = "Saved setups. Apply one to restore its full multi-kit selection, then review and install.",
        ["profiles.empty"] = "No profiles yet. Make a selection and use \"Save as profile\" on the review page.",
        ["profiles.apply"] = "Apply & review",
        ["profiles.deletetitle"] = "Delete profile?",
        ["profiles.deletebody"] = "Delete \"{0}\"?",
        ["profiles.items"] = "{0} item(s) · saved {1}",

        ["editor.title"] = "Kit Editor",
        ["editor.newkit"] = "New kit",
        ["editor.kit"] = "Kit",
        ["editor.name"] = "Name",
        ["editor.icon"] = "Icon (Segoe Fluent Icons glyph)",
        ["editor.description"] = "Description",
        ["editor.pages"] = "Pages (wizard steps)",
        ["editor.addpage"] = "Add page",
        ["editor.removepage"] = "Remove page",
        ["editor.selectedpage"] = "Selected page",
        ["editor.pageid"] = "Page id (used for branching)",
        ["editor.question"] = "Question",
        ["editor.multiselect"] = "Allow multiple selections (off = single choice)",
        ["editor.condpage"] = "Only show if page id… (optional branch condition)",
        ["editor.condchoice"] = "…has this choice selected (optional)",
        ["editor.choices"] = "Choices",
        ["editor.addchoice"] = "Add choice",
        ["editor.removechoice"] = "Remove choice",
        ["editor.selectedchoice"] = "Selected choice",
        ["editor.choiceid"] = "Choice id",
        ["editor.action"] = "Install action",
        ["editor.target"] = "Target",
        ["editor.args"] = "Arguments",
        ["editor.source"] = "winget source (optional: winget or msstore)",
        ["editor.dependson"] = "Depends on (choice ids in this kit, comma separated)",
        ["editor.admin"] = "Requires administrator",
        ["editor.save"] = "Save kit",
        ["editor.saved"] = "Saved {0} ({1} pages).",
        ["editor.builtin"] = "Built-in kit — saving stores an edited copy as your own version.",
        ["editor.builtin.title"] = "Built-in kit",
        ["editor.builtin.body"] = "Built-in kits can't be deleted. Duplicate it and edit the copy instead.",
        ["editor.deletetitle"] = "Delete kit?",
        ["editor.deletebody"] = "Delete \"{0}\"?",
        ["editor.importfail.title"] = "Import failed",
        ["editor.importfail.body"] = "That file is not a valid .provisio-kit.",

        ["editor.hint.none"] = "This choice installs nothing. Use it for yes/no branch questions.",
        ["editor.hint.winget"] = "Target = winget package id, e.g. Microsoft.PowerToys. Use the source field for msstore packages.",
        ["editor.hint.download"] = "Target = direct download URL. Supported formats: .exe, .msi, .msix, .msixbundle, .appx, .appxbundle. MSIX/APPX bundles are detected automatically and installed with Add-AppxPackage; .exe/.msi installers are run with the silent-install arguments below.",
        ["editor.hint.msix"] = "Target = direct URL to an MSIX bundle (.msix, .msixbundle, .appx, .appxbundle). Downloaded and installed with Add-AppxPackage. A local file path works too.",
        ["editor.hint.shell"] = "Target = a shell command line, run through cmd.exe, e.g. npm install -g @anthropic-ai/claude-code. Use it for package managers (npm, pip, uv, scoop, choco) and setup tasks.",
        ["editor.hint.script"] = "Target = a PowerShell script body. Tick \"Requires administrator\" for anything touching HKLM or system settings.",
        ["editor.args.download"] = "Silent-install args (e.g. /S or /quiet)",
        ["editor.args.shell"] = "Extra arguments (appended to the command)",
        ["editor.target.winget"] = "Package id",
        ["editor.target.download"] = "Download URL",
        ["editor.target.msix"] = "MSIX bundle URL or path",
        ["editor.target.shell"] = "Shell command",
        ["editor.target.script"] = "PowerShell script",

        ["settings.title"] = "Settings",
        ["settings.appearance"] = "Appearance",
        ["settings.appearance.desc"] = "Theme applies immediately to the whole app.",
        ["settings.theme"] = "Theme",
        ["settings.theme.system"] = "Use system setting",
        ["settings.theme.light"] = "Light",
        ["settings.theme.dark"] = "Dark",
        ["settings.language"] = "Language",
        ["settings.language.desc"] = "Language of the Provisio interface. Kit names and descriptions come from the kit files and are not translated.",
        ["settings.language.label"] = "Interface language",
        ["settings.packages"] = "Package updates",
        ["settings.packages.desc"] = "Provisio can detect newer versions of software installed on this PC (through winget) and update them for you.",
        ["settings.packages.check"] = "Check for package updates when Provisio starts",
        ["settings.packages.auto"] = "Install available package updates automatically in the background",
        ["settings.packages.open"] = "Open the Updates page",
        ["settings.appupdates"] = "Provisio updates",
        ["settings.appupdates.desc"] = "URL of an update feed (JSON with appVersion, downloadUrl, and optional kit definitions). Checked on launch.",
        ["settings.checknow"] = "Check now",
        ["settings.version"] = "Provisio {0}",
        ["settings.offline"] = "Offline / portable mode",
        ["settings.cache"] = "Cache downloaded installers for re-use without re-downloading",
        ["settings.cachepath"] = "Installer cache: {0}",
        ["settings.data"] = "Data & first run",
        ["settings.data.desc"] = "Kits, profiles, cached installers and settings live in your local app data folder.",
        ["settings.data.open"] = "Open data folder",
        ["settings.data.clearcache"] = "Clear installer cache",
        ["settings.data.resetpopups"] = "Show first-run pop-ups again",
        ["settings.data.cleared"] = "Installer cache cleared.",
        ["settings.data.reset"] = "The welcome and import-warning pop-ups will be shown again.",
        ["settings.about"] = "About",
        ["settings.about.body"] = "Provisio — a first-run setup wizard for Windows. Kits, profiles and custom actions are stored as plain JSON so you can share and inspect them.",
        ["settings.updatecheck.title"] = "Update check",
        ["settings.updatecheck.nourl"] = "No update feed URL configured.",
        ["settings.updatecheck.found"] = "Version {0} is available.",
        ["settings.updatecheck.none"] = "No update found (or the feed is unreachable).",

        ["updates.title"] = "Package updates",
        ["updates.subtitle"] = "Software already installed on this PC that has a newer version available through winget.",
        ["updates.check"] = "Check for updates",
        ["updates.checking"] = "Checking for updates…",
        ["updates.none"] = "Everything is up to date.",
        ["updates.found"] = "{0} update(s) available.",
        ["updates.updateselected"] = "Update selected",
        ["updates.updateall"] = "Update all",
        ["updates.col.package"] = "Package",
        ["updates.col.installed"] = "Installed",
        ["updates.col.available"] = "Available",
        ["updates.running"] = "Updating {0}…",
        ["updates.finished"] = "Finished. {0} updated, {1} failed.",
        ["updates.nowinget"] = "winget (App Installer) was not found on this PC. Install \"App Installer\" from the Microsoft Store to use package updates.",
        ["updates.autorunning"] = "Installing package updates in the background…",
        ["updates.notchecked"] = "Not checked yet.",
        ["updates.available.bar"] = "{0} package update(s) are available.",
        ["updates.available.show"] = "Show",

        ["rec.title"] = "Recommended Setup",
        ["rec.subtitle"] = "Answer a few questions about how you use this PC. Provisio then compiles a curated, cross-kit list of software and tweaks for your profile — you decide what actually gets queued.",
        ["rec.start"] = "Start questionnaire",
        ["rec.step"] = "Question {0} of {1}",
        ["rec.multi"] = "Pick everything that applies.",
        ["rec.single"] = "Pick one.",
        ["rec.finish"] = "Show recommendations",
        ["rec.results.title"] = "Your recommended setup",
        ["rec.results.subtitle"] = "{0} suggestion(s) across {1} kit(s), based on your answers. Uncheck anything you don't want, then add the rest to your setup.",
        ["rec.results.empty"] = "Your answers didn't match any recommendations. Try the questionnaire again with more options selected, or browse the kits directly.",
        ["rec.add"] = "Add to my setup",
        ["rec.restart"] = "Start over",
        ["rec.why"] = "Because you chose: {0}",
        ["rec.added.title"] = "Added to your setup",
        ["rec.added.body"] = "{0} item(s) were queued. Review them and start the installation whenever you're ready.",

        ["rec.q.use"] = "What do you mainly use this PC for?",
        ["rec.q.use.general"] = "Everyday use — browsing, mail, media",
        ["rec.q.use.work"] = "Work — documents, meetings, notes",
        ["rec.q.use.dev"] = "Software development",
        ["rec.q.use.gaming"] = "Gaming",
        ["rec.q.level"] = "How would you describe yourself?",
        ["rec.q.level.beginner"] = "Beginner — I want it to just work",
        ["rec.q.level.confident"] = "Confident — I tweak things now and then",
        ["rec.q.level.power"] = "Power user — give me the tools and shortcuts",
        ["rec.q.browser"] = "Which browser do you want?",
        ["rec.q.browser.chrome"] = "Google Chrome",
        ["rec.q.browser.firefox"] = "Mozilla Firefox",
        ["rec.q.browser.brave"] = "Something privacy-focused",
        ["rec.q.browser.keep"] = "I'll keep what's already installed",
        ["rec.q.privacy"] = "How much do you care about privacy?",
        ["rec.q.privacy.default"] = "Windows defaults are fine",
        ["rec.q.privacy.some"] = "Turn off tracking and ads where easy",
        ["rec.q.privacy.max"] = "Harden everything — encryption, VPN, firewall",
        ["rec.q.ai"] = "How do you want to use AI?",
        ["rec.q.ai.none"] = "Not at all",
        ["rec.q.ai.chat"] = "Desktop chat apps",
        ["rec.q.ai.cli"] = "Coding agents in the terminal",
        ["rec.q.ai.local"] = "Run models locally on this PC",
        ["rec.q.dev"] = "What do you build?",
        ["rec.q.dev.none"] = "Nothing / not applicable",
        ["rec.q.dev.web"] = "Web and JavaScript",
        ["rec.q.dev.python"] = "Python, data or scripting",
        ["rec.q.dev.dotnet"] = "C# / .NET or desktop apps",
        ["rec.q.office"] = "What do you need for documents?",
        ["rec.q.office.none"] = "Nothing special",
        ["rec.q.office.free"] = "A free office suite",
        ["rec.q.office.ms"] = "Microsoft Office / 365",
        ["rec.q.office.notes"] = "Notes and knowledge base",
        ["rec.q.gaming"] = "How do you game?",
        ["rec.q.gaming.none"] = "I don't game on this PC",
        ["rec.q.gaming.casual"] = "Occasionally, mostly Steam",
        ["rec.q.gaming.serious"] = "A lot, across several stores",
        ["rec.q.gaming.stream"] = "I record or stream my sessions",
        ["rec.q.creative"] = "Do you create media?",
        ["rec.q.creative.none"] = "No",
        ["rec.q.creative.image"] = "Photos and graphics",
        ["rec.q.creative.video"] = "Video and audio",
        ["rec.q.creative.3d"] = "3D and animation",
        ["rec.q.tweaks"] = "Should Provisio adjust Windows itself?",
        ["rec.q.tweaks.none"] = "No, leave Windows alone",
        ["rec.q.tweaks.quality"] = "Yes — quality-of-life tweaks",
        ["rec.q.tweaks.debloat"] = "Yes — and remove preinstalled bloatware",
    };

    // ----------------------------------------------------------------- German

    private static Dictionary<string, string> De => new()
    {
        ["nav.kits"] = "Kits",
        ["nav.recommend"] = "Empfehlung",
        ["nav.search"] = "Suche",
        ["nav.profiles"] = "Profile",
        ["nav.editor"] = "Kit-Editor",
        ["nav.updates"] = "Updates",
        ["nav.settings"] = "Einstellungen",

        ["common.back"] = "Zurück",
        ["common.next"] = "Weiter",
        ["common.skip"] = "Schritt überspringen",
        ["common.cancel"] = "Abbrechen",
        ["common.close"] = "Schließen",
        ["common.ok"] = "OK",
        ["common.save"] = "Speichern",
        ["common.delete"] = "Löschen",
        ["common.import"] = "Importieren",
        ["common.export"] = "Exportieren",
        ["common.duplicate"] = "Duplizieren",
        ["common.done"] = "Fertig",
        ["common.retry"] = "Fehlgeschlagene wiederholen",
        ["common.yes"] = "Ja",
        ["common.no"] = "Nein",
        ["common.continue"] = "Fortfahren",
        ["common.refresh"] = "Aktualisieren",
        ["common.selectall"] = "Alle auswählen",
        ["common.clear"] = "Leeren",
        ["common.updating"] = "Wird aktualisiert…",
        ["common.failed"] = "Fehlgeschlagen",
        ["status.queued"] = "Vorgemerkt",
        ["status.downloading"] = "Wird geladen…",
        ["status.installing"] = "Wird installiert…",
        ["status.skipped"] = "Übersprungen",

        ["update.available"] = "Provisio {0} ist verfügbar (installiert: {1}). {2}",
        ["update.download"] = "Herunterladen",

        ["welcome.title"] = "Willkommen bei Provisio",
        ["welcome.body"] = "Danke, dass du Provisio heruntergeladen hast! Provisio ist ein Einrichtungsassistent für Windows: Kits auswählen, ein paar Fragen beantworten, alles prüfen — und Provisio installiert alles in einem Durchgang.\n\nEs wird nichts installiert, bevor du es auf der Übersichtsseite bestätigst.",
        ["welcome.hint"] = "Tipp: Du weißt nicht, wo du anfangen sollst? Probiere „Empfehlung“ — ein kurzer Fragebogen stellt dir ein Setup zusammen.",
        ["welcome.start"] = "Kits ansehen",
        ["welcome.recommend"] = "Empfohlenes Setup starten",

        ["security.title"] = "Bevor du ein Community-Kit importierst",
        ["security.body"] = "Kits sind nicht nur Listen von Programmen: Sie können Shell-Befehle, PowerShell-Skripte und heruntergeladene Installer mit deinem Benutzerkonto ausführen — und, wenn das Kit es verlangt, als Administrator.\n\nImportiere nur Kits aus Quellen, denen du vertraust. Öffne ein importiertes Kit zuerst im Kit-Editor und lies jede Aktion (winget-Id, Download-URL, Shell-Befehl oder Skript), bevor du etwas daraus installierst.",
        ["security.ack"] = "Verstanden, fortfahren",
        ["security.info"] = "Dieser Hinweis wird nur einmal angezeigt. Importierte Kits erscheinen immer zuerst im Kit-Editor, bevor etwas ausgeführt wird.",

        ["kits.title"] = "Willkommen bei Provisio",
        ["kits.subtitle"] = "Wähle die Kits aus, die du einrichten möchtest. Es wird nichts installiert, bis du am Ende bestätigst.",
        ["kits.review"] = "Auswahl prüfen",
        ["kits.start"] = "Einrichtung starten",
        ["kits.none"] = "Keine Kits ausgewählt",
        ["kits.count"] = "{0} Kits ausgewählt",
        ["kits.count.one"] = "1 Kit ausgewählt",
        ["kits.nonetitle"] = "Keine Kits ausgewählt",
        ["kits.nonebody"] = "Wähle mindestens ein Kit aus, um den Assistenten zu starten.",

        ["wizard.kitof"] = "Kit {0} von {1} — {2}",
        ["wizard.step"] = "Schritt {0} von {1}",
        ["wizard.review"] = "Übersicht",
        ["wizard.nextkit"] = "Nächstes Kit",

        ["summary.title"] = "Setup prüfen",
        ["summary.subtitle"] = "Alles, was bisher vorgemerkt ist. Haken entfernen, was du nicht willst — installiert wurde noch nichts.",
        ["summary.saveprofile"] = "Als Profil speichern",
        ["summary.preview"] = "Befehle anzeigen",
        ["summary.install"] = "Installieren",
        ["summary.empty"] = "Noch nichts vorgemerkt. Gehe zurück und wähle Software oder Anpassungen aus.",
        ["summary.previewtitle"] = "Testlauf — genau diese Befehle werden ausgeführt",
        ["summary.nothingqueued"] = "Nichts vorgemerkt.",
        ["summary.profiletitle"] = "Auswahl als Profil speichern",
        ["summary.profilename"] = "Profilname",

        ["install.title"] = "Installation",
        ["install.ready"] = "Bereit. Es wird ein Eintrag nach dem anderen installiert; Fehler stoppen den Rest nicht.",
        ["install.nothing"] = "Nichts vorgemerkt.",
        ["install.admin"] = "Einige Aktionen benötigen Administratorrechte. Starte Provisio als Administrator neu.",
        ["install.restartadmin"] = "Als Administrator neu starten",
        ["install.exportlog"] = "Protokoll exportieren",
        ["install.start"] = "Installation starten",
        ["install.restore.on"] = "Wiederherstellungspunkt: an",
        ["install.restore.off"] = "Wiederherstellungspunkt: aus",
        ["install.creatingrestore"] = "Wiederherstellungspunkt wird erstellt…",
        ["install.running"] = "{0} wird installiert…",
        ["install.alldone"] = "Alles erledigt.",
        ["install.failed"] = "Abgeschlossen mit {0} Fehler(n). Du kannst die fehlgeschlagenen Einträge wiederholen.",

        ["search.title"] = "Alles durchsuchen",
        ["search.placeholder"] = "Programme und Anpassungen in allen Kits finden…",
        ["search.queue"] = "Vormerken",
        ["search.queued"] = "Vorgemerkt",

        ["profiles.title"] = "Profile",
        ["profiles.subtitle"] = "Gespeicherte Setups. Ein Profil stellt die komplette Auswahl über alle Kits wieder her.",
        ["profiles.empty"] = "Noch keine Profile. Triff eine Auswahl und nutze „Als Profil speichern“ auf der Übersichtsseite.",
        ["profiles.apply"] = "Anwenden & prüfen",
        ["profiles.deletetitle"] = "Profil löschen?",
        ["profiles.deletebody"] = "„{0}“ löschen?",
        ["profiles.items"] = "{0} Eintrag/Einträge · gespeichert {1}",

        ["editor.title"] = "Kit-Editor",
        ["editor.newkit"] = "Neues Kit",
        ["editor.kit"] = "Kit",
        ["editor.name"] = "Name",
        ["editor.icon"] = "Symbol (Segoe Fluent Icons Zeichen)",
        ["editor.description"] = "Beschreibung",
        ["editor.pages"] = "Seiten (Assistenten-Schritte)",
        ["editor.addpage"] = "Seite hinzufügen",
        ["editor.removepage"] = "Seite entfernen",
        ["editor.selectedpage"] = "Ausgewählte Seite",
        ["editor.pageid"] = "Seiten-Id (für Verzweigungen)",
        ["editor.question"] = "Frage",
        ["editor.multiselect"] = "Mehrfachauswahl erlauben (aus = Einzelauswahl)",
        ["editor.condpage"] = "Nur anzeigen, wenn Seiten-Id… (optionale Bedingung)",
        ["editor.condchoice"] = "…diese Option ausgewählt hat (optional)",
        ["editor.choices"] = "Optionen",
        ["editor.addchoice"] = "Option hinzufügen",
        ["editor.removechoice"] = "Option entfernen",
        ["editor.selectedchoice"] = "Ausgewählte Option",
        ["editor.choiceid"] = "Options-Id",
        ["editor.action"] = "Installationsaktion",
        ["editor.target"] = "Ziel",
        ["editor.args"] = "Argumente",
        ["editor.source"] = "winget-Quelle (optional: winget oder msstore)",
        ["editor.dependson"] = "Hängt ab von (Options-Ids in diesem Kit, mit Komma getrennt)",
        ["editor.admin"] = "Benötigt Administrator",
        ["editor.save"] = "Kit speichern",
        ["editor.saved"] = "{0} gespeichert ({1} Seiten).",
        ["editor.builtin"] = "Mitgeliefertes Kit — beim Speichern wird eine eigene, bearbeitete Kopie angelegt.",
        ["editor.builtin.title"] = "Mitgeliefertes Kit",
        ["editor.builtin.body"] = "Mitgelieferte Kits können nicht gelöscht werden. Dupliziere das Kit und bearbeite die Kopie.",
        ["editor.deletetitle"] = "Kit löschen?",
        ["editor.deletebody"] = "„{0}“ löschen?",
        ["editor.importfail.title"] = "Import fehlgeschlagen",
        ["editor.importfail.body"] = "Diese Datei ist kein gültiges .provisio-kit.",

        ["editor.hint.none"] = "Diese Option installiert nichts. Nutze sie für Ja/Nein-Verzweigungsfragen.",
        ["editor.hint.winget"] = "Ziel = winget-Paket-Id, z. B. Microsoft.PowerToys. Für Store-Pakete das Quellfeld nutzen.",
        ["editor.hint.download"] = "Ziel = direkte Download-URL. Unterstützte Formate: .exe, .msi, .msix, .msixbundle, .appx, .appxbundle. MSIX-/APPX-Bundles werden automatisch erkannt und mit Add-AppxPackage installiert; .exe/.msi werden mit den Silent-Argumenten unten ausgeführt.",
        ["editor.hint.msix"] = "Ziel = direkte URL zu einem MSIX-Bundle (.msix, .msixbundle, .appx, .appxbundle). Wird heruntergeladen und mit Add-AppxPackage installiert. Ein lokaler Dateipfad funktioniert ebenfalls.",
        ["editor.hint.shell"] = "Ziel = eine Befehlszeile, ausgeführt über cmd.exe, z. B. npm install -g @anthropic-ai/claude-code. Ideal für Paketmanager (npm, pip, uv, scoop, choco) und Einrichtungsaufgaben.",
        ["editor.hint.script"] = "Ziel = ein PowerShell-Skript. Aktiviere „Benötigt Administrator“ für alles, was HKLM oder Systemeinstellungen anfasst.",
        ["editor.args.download"] = "Silent-Argumente (z. B. /S oder /quiet)",
        ["editor.args.shell"] = "Zusätzliche Argumente (werden angehängt)",
        ["editor.target.winget"] = "Paket-Id",
        ["editor.target.download"] = "Download-URL",
        ["editor.target.msix"] = "MSIX-Bundle: URL oder Pfad",
        ["editor.target.shell"] = "Shell-Befehl",
        ["editor.target.script"] = "PowerShell-Skript",

        ["settings.title"] = "Einstellungen",
        ["settings.appearance"] = "Darstellung",
        ["settings.appearance.desc"] = "Das Design wird sofort auf die gesamte App angewendet.",
        ["settings.theme"] = "Design",
        ["settings.theme.system"] = "Systemeinstellung verwenden",
        ["settings.theme.light"] = "Hell",
        ["settings.theme.dark"] = "Dunkel",
        ["settings.language"] = "Sprache",
        ["settings.language.desc"] = "Sprache der Provisio-Oberfläche. Kit-Namen und -Beschreibungen stammen aus den Kit-Dateien und werden nicht übersetzt.",
        ["settings.language.label"] = "Sprache der Oberfläche",
        ["settings.packages"] = "Paket-Updates",
        ["settings.packages.desc"] = "Provisio kann neuere Versionen der auf diesem PC installierten Software erkennen (über winget) und sie für dich aktualisieren.",
        ["settings.packages.check"] = "Beim Start von Provisio nach Paket-Updates suchen",
        ["settings.packages.auto"] = "Verfügbare Paket-Updates automatisch im Hintergrund installieren",
        ["settings.packages.open"] = "Update-Seite öffnen",
        ["settings.appupdates"] = "Provisio-Updates",
        ["settings.appupdates.desc"] = "URL eines Update-Feeds (JSON mit appVersion, downloadUrl und optionalen Kit-Definitionen). Wird beim Start geprüft.",
        ["settings.checknow"] = "Jetzt prüfen",
        ["settings.version"] = "Provisio {0}",
        ["settings.offline"] = "Offline- / Portabel-Modus",
        ["settings.cache"] = "Heruntergeladene Installer zwischenspeichern und wiederverwenden",
        ["settings.cachepath"] = "Installer-Cache: {0}",
        ["settings.data"] = "Daten & Erststart",
        ["settings.data.desc"] = "Kits, Profile, zwischengespeicherte Installer und Einstellungen liegen im lokalen App-Datenordner.",
        ["settings.data.open"] = "Datenordner öffnen",
        ["settings.data.clearcache"] = "Installer-Cache leeren",
        ["settings.data.resetpopups"] = "Erststart-Hinweise erneut anzeigen",
        ["settings.data.cleared"] = "Installer-Cache geleert.",
        ["settings.data.reset"] = "Willkommens- und Import-Hinweis werden wieder angezeigt.",
        ["settings.about"] = "Über",
        ["settings.about.body"] = "Provisio — ein Einrichtungsassistent für Windows. Kits, Profile und eigene Aktionen werden als einfaches JSON gespeichert, damit du sie teilen und prüfen kannst.",
        ["settings.updatecheck.title"] = "Update-Prüfung",
        ["settings.updatecheck.nourl"] = "Keine Update-Feed-URL konfiguriert.",
        ["settings.updatecheck.found"] = "Version {0} ist verfügbar.",
        ["settings.updatecheck.none"] = "Kein Update gefunden (oder der Feed ist nicht erreichbar).",

        ["updates.title"] = "Paket-Updates",
        ["updates.subtitle"] = "Bereits installierte Software, für die über winget eine neuere Version verfügbar ist.",
        ["updates.check"] = "Nach Updates suchen",
        ["updates.checking"] = "Suche nach Updates…",
        ["updates.none"] = "Alles ist auf dem neuesten Stand.",
        ["updates.found"] = "{0} Update(s) verfügbar.",
        ["updates.updateselected"] = "Ausgewählte aktualisieren",
        ["updates.updateall"] = "Alle aktualisieren",
        ["updates.col.package"] = "Paket",
        ["updates.col.installed"] = "Installiert",
        ["updates.col.available"] = "Verfügbar",
        ["updates.running"] = "{0} wird aktualisiert…",
        ["updates.finished"] = "Fertig. {0} aktualisiert, {1} fehlgeschlagen.",
        ["updates.nowinget"] = "winget (App Installer) wurde auf diesem PC nicht gefunden. Installiere „App Installer“ aus dem Microsoft Store, um Paket-Updates zu nutzen.",
        ["updates.autorunning"] = "Paket-Updates werden im Hintergrund installiert…",
        ["updates.notchecked"] = "Noch nicht geprüft.",
        ["updates.available.bar"] = "{0} Paket-Update(s) verfügbar.",
        ["updates.available.show"] = "Anzeigen",

        ["rec.title"] = "Empfohlenes Setup",
        ["rec.subtitle"] = "Beantworte ein paar Fragen dazu, wie du diesen PC nutzt. Provisio stellt daraus eine kuratierte Liste aus allen Kits zusammen — was tatsächlich vorgemerkt wird, entscheidest du.",
        ["rec.start"] = "Fragebogen starten",
        ["rec.step"] = "Frage {0} von {1}",
        ["rec.multi"] = "Wähle alles aus, was zutrifft.",
        ["rec.single"] = "Wähle eine Option.",
        ["rec.finish"] = "Empfehlungen anzeigen",
        ["rec.results.title"] = "Dein empfohlenes Setup",
        ["rec.results.subtitle"] = "{0} Vorschläge aus {1} Kit(s), basierend auf deinen Antworten. Entferne den Haken bei allem, was du nicht willst, und übernimm den Rest.",
        ["rec.results.empty"] = "Deine Antworten haben zu keinen Empfehlungen geführt. Starte den Fragebogen erneut mit mehr Auswahlen oder sieh dir die Kits direkt an.",
        ["rec.add"] = "Zu meinem Setup hinzufügen",
        ["rec.restart"] = "Von vorn beginnen",
        ["rec.why"] = "Weil du gewählt hast: {0}",
        ["rec.added.title"] = "Zum Setup hinzugefügt",
        ["rec.added.body"] = "{0} Eintrag/Einträge wurden vorgemerkt. Prüfe sie und starte die Installation, wenn du bereit bist.",

        ["rec.q.use"] = "Wofür nutzt du diesen PC hauptsächlich?",
        ["rec.q.use.general"] = "Alltag — Surfen, Mail, Medien",
        ["rec.q.use.work"] = "Arbeit — Dokumente, Meetings, Notizen",
        ["rec.q.use.dev"] = "Softwareentwicklung",
        ["rec.q.use.gaming"] = "Gaming",
        ["rec.q.level"] = "Wie würdest du dich selbst beschreiben?",
        ["rec.q.level.beginner"] = "Einsteiger — es soll einfach funktionieren",
        ["rec.q.level.confident"] = "Erfahren — ich passe ab und zu etwas an",
        ["rec.q.level.power"] = "Power-User — gib mir Werkzeuge und Shortcuts",
        ["rec.q.browser"] = "Welchen Browser möchtest du?",
        ["rec.q.browser.chrome"] = "Google Chrome",
        ["rec.q.browser.firefox"] = "Mozilla Firefox",
        ["rec.q.browser.brave"] = "Etwas mit Fokus auf Privatsphäre",
        ["rec.q.browser.keep"] = "Ich behalte, was schon installiert ist",
        ["rec.q.privacy"] = "Wie wichtig ist dir Privatsphäre?",
        ["rec.q.privacy.default"] = "Die Windows-Voreinstellungen reichen mir",
        ["rec.q.privacy.some"] = "Tracking und Werbung abschalten, wo es einfach geht",
        ["rec.q.privacy.max"] = "Alles härten — Verschlüsselung, VPN, Firewall",
        ["rec.q.ai"] = "Wie möchtest du KI nutzen?",
        ["rec.q.ai.none"] = "Gar nicht",
        ["rec.q.ai.chat"] = "Desktop-Chat-Apps",
        ["rec.q.ai.cli"] = "Coding-Agenten im Terminal",
        ["rec.q.ai.local"] = "Modelle lokal auf diesem PC ausführen",
        ["rec.q.dev"] = "Was entwickelst du?",
        ["rec.q.dev.none"] = "Nichts / trifft nicht zu",
        ["rec.q.dev.web"] = "Web und JavaScript",
        ["rec.q.dev.python"] = "Python, Daten oder Skripte",
        ["rec.q.dev.dotnet"] = "C# / .NET oder Desktop-Apps",
        ["rec.q.office"] = "Was brauchst du für Dokumente?",
        ["rec.q.office.none"] = "Nichts Besonderes",
        ["rec.q.office.free"] = "Ein kostenloses Office-Paket",
        ["rec.q.office.ms"] = "Microsoft Office / 365",
        ["rec.q.office.notes"] = "Notizen und Wissensdatenbank",
        ["rec.q.gaming"] = "Wie spielst du?",
        ["rec.q.gaming.none"] = "Ich spiele nicht an diesem PC",
        ["rec.q.gaming.casual"] = "Gelegentlich, hauptsächlich Steam",
        ["rec.q.gaming.serious"] = "Viel, über mehrere Stores",
        ["rec.q.gaming.stream"] = "Ich nehme auf oder streame",
        ["rec.q.creative"] = "Erstellst du Medien?",
        ["rec.q.creative.none"] = "Nein",
        ["rec.q.creative.image"] = "Fotos und Grafik",
        ["rec.q.creative.video"] = "Video und Audio",
        ["rec.q.creative.3d"] = "3D und Animation",
        ["rec.q.tweaks"] = "Soll Provisio Windows selbst anpassen?",
        ["rec.q.tweaks.none"] = "Nein, Windows unverändert lassen",
        ["rec.q.tweaks.quality"] = "Ja — Komfort-Anpassungen",
        ["rec.q.tweaks.debloat"] = "Ja — und vorinstallierte Bloatware entfernen",
    };

    // ---------------------------------------------------------------- Spanish

    private static Dictionary<string, string> Es => new()
    {
        ["nav.kits"] = "Kits",
        ["nav.recommend"] = "Recomendado",
        ["nav.search"] = "Buscar",
        ["nav.profiles"] = "Perfiles",
        ["nav.editor"] = "Editor de kits",
        ["nav.updates"] = "Actualizaciones",
        ["nav.settings"] = "Ajustes",

        ["common.back"] = "Atrás",
        ["common.next"] = "Siguiente",
        ["common.skip"] = "Omitir este paso",
        ["common.cancel"] = "Cancelar",
        ["common.close"] = "Cerrar",
        ["common.ok"] = "Aceptar",
        ["common.save"] = "Guardar",
        ["common.delete"] = "Eliminar",
        ["common.import"] = "Importar",
        ["common.export"] = "Exportar",
        ["common.duplicate"] = "Duplicar",
        ["common.done"] = "Listo",
        ["common.retry"] = "Reintentar fallidos",
        ["common.yes"] = "Sí",
        ["common.no"] = "No",
        ["common.continue"] = "Continuar",
        ["common.refresh"] = "Actualizar",
        ["common.selectall"] = "Seleccionar todo",
        ["common.clear"] = "Vaciar",
        ["common.updating"] = "Actualizando…",
        ["common.failed"] = "Fallido",
        ["status.queued"] = "En cola",
        ["status.downloading"] = "Descargando…",
        ["status.installing"] = "Instalando…",
        ["status.skipped"] = "Omitido",

        ["update.available"] = "Provisio {0} está disponible (tienes {1}). {2}",
        ["update.download"] = "Descargar",

        ["welcome.title"] = "Bienvenido a Provisio",
        ["welcome.body"] = "¡Gracias por descargar Provisio! Es un asistente de configuración inicial para Windows: elige los kits que quieras, responde unas preguntas, revisa todo y Provisio lo instala en un solo lote.\n\nNunca se instala nada hasta que lo confirmas en la pantalla de revisión.",
        ["welcome.hint"] = "Consejo: si no sabes por dónde empezar, prueba «Recomendado» — un cuestionario corto que arma la configuración por ti.",
        ["welcome.start"] = "Ver los kits",
        ["welcome.recommend"] = "Iniciar configuración recomendada",

        ["security.title"] = "Antes de importar un kit de la comunidad",
        ["security.body"] = "Los kits no son solo listas de programas: pueden ejecutar comandos de shell, scripts de PowerShell e instaladores descargados con tu cuenta y, si el kit lo pide, como administrador.\n\nImporta kits solo de fuentes en las que confíes. Abre el kit en el Editor de kits y lee cada acción (id de winget, URL de descarga, comando o script) antes de instalar nada.",
        ["security.ack"] = "Entendido, continuar",
        ["security.info"] = "Este aviso se muestra una sola vez. Los kits importados siempre aparecen en el Editor de kits antes de ejecutar nada.",

        ["kits.title"] = "Bienvenido a Provisio",
        ["kits.subtitle"] = "Elige los kits que quieres configurar. No se instala nada hasta que revises y confirmes al final.",
        ["kits.review"] = "Revisar selección",
        ["kits.start"] = "Iniciar configuración",
        ["kits.none"] = "Ningún kit seleccionado",
        ["kits.count"] = "{0} kits seleccionados",
        ["kits.count.one"] = "1 kit seleccionado",
        ["kits.nonetitle"] = "Ningún kit seleccionado",
        ["kits.nonebody"] = "Selecciona al menos un kit para iniciar el asistente.",

        ["wizard.kitof"] = "Kit {0} de {1} — {2}",
        ["wizard.step"] = "Paso {0} de {1}",
        ["wizard.review"] = "Revisar",
        ["wizard.nextkit"] = "Siguiente kit",

        ["summary.title"] = "Revisa tu configuración",
        ["summary.subtitle"] = "Todo lo que está en cola. Desmarca lo que no quieras: aún no se ha instalado nada.",
        ["summary.saveprofile"] = "Guardar como perfil",
        ["summary.preview"] = "Ver comandos",
        ["summary.install"] = "Instalar",
        ["summary.empty"] = "Todavía no hay nada en cola. Vuelve atrás y elige programas o ajustes.",
        ["summary.previewtitle"] = "Simulación — comandos exactos que se ejecutarán",
        ["summary.nothingqueued"] = "Nada en cola.",
        ["summary.profiletitle"] = "Guardar selección como perfil",
        ["summary.profilename"] = "Nombre del perfil",

        ["install.title"] = "Instalando",
        ["install.ready"] = "Listo. Se instala un elemento a la vez; los fallos no detienen el resto.",
        ["install.nothing"] = "Nada en cola.",
        ["install.admin"] = "Algunas acciones necesitan permisos de administrador. Reinicia Provisio como administrador.",
        ["install.restartadmin"] = "Reiniciar como administrador",
        ["install.exportlog"] = "Exportar registro",
        ["install.start"] = "Iniciar instalación",
        ["install.restore.on"] = "Punto de restauración: sí",
        ["install.restore.off"] = "Punto de restauración: no",
        ["install.creatingrestore"] = "Creando punto de restauración…",
        ["install.running"] = "Instalando {0}…",
        ["install.alldone"] = "Todo listo.",
        ["install.failed"] = "Finalizado con {0} fallo(s). Puedes reintentar los elementos fallidos.",

        ["search.title"] = "Buscar en todo",
        ["search.placeholder"] = "Busca programas y ajustes en todos los kits…",
        ["search.queue"] = "Añadir",
        ["search.queued"] = "Añadido",

        ["profiles.title"] = "Perfiles",
        ["profiles.subtitle"] = "Configuraciones guardadas. Aplica una para restaurar toda la selección de varios kits.",
        ["profiles.empty"] = "Aún no hay perfiles. Haz una selección y usa «Guardar como perfil» en la pantalla de revisión.",
        ["profiles.apply"] = "Aplicar y revisar",
        ["profiles.deletetitle"] = "¿Eliminar perfil?",
        ["profiles.deletebody"] = "¿Eliminar «{0}»?",
        ["profiles.items"] = "{0} elemento(s) · guardado {1}",

        ["editor.title"] = "Editor de kits",
        ["editor.newkit"] = "Nuevo kit",
        ["editor.kit"] = "Kit",
        ["editor.name"] = "Nombre",
        ["editor.icon"] = "Icono (glifo de Segoe Fluent Icons)",
        ["editor.description"] = "Descripción",
        ["editor.pages"] = "Páginas (pasos del asistente)",
        ["editor.addpage"] = "Añadir página",
        ["editor.removepage"] = "Quitar página",
        ["editor.selectedpage"] = "Página seleccionada",
        ["editor.pageid"] = "Id de página (para ramificaciones)",
        ["editor.question"] = "Pregunta",
        ["editor.multiselect"] = "Permitir varias selecciones (apagado = una sola)",
        ["editor.condpage"] = "Mostrar solo si la página… (condición opcional)",
        ["editor.condchoice"] = "…tiene esta opción seleccionada (opcional)",
        ["editor.choices"] = "Opciones",
        ["editor.addchoice"] = "Añadir opción",
        ["editor.removechoice"] = "Quitar opción",
        ["editor.selectedchoice"] = "Opción seleccionada",
        ["editor.choiceid"] = "Id de opción",
        ["editor.action"] = "Acción de instalación",
        ["editor.target"] = "Destino",
        ["editor.args"] = "Argumentos",
        ["editor.source"] = "Fuente winget (opcional: winget o msstore)",
        ["editor.dependson"] = "Depende de (ids de opciones de este kit, separadas por comas)",
        ["editor.admin"] = "Requiere administrador",
        ["editor.save"] = "Guardar kit",
        ["editor.saved"] = "{0} guardado ({1} páginas).",
        ["editor.builtin"] = "Kit incluido — al guardar se crea una copia editada tuya.",
        ["editor.builtin.title"] = "Kit incluido",
        ["editor.builtin.body"] = "Los kits incluidos no se pueden eliminar. Duplícalo y edita la copia.",
        ["editor.deletetitle"] = "¿Eliminar kit?",
        ["editor.deletebody"] = "¿Eliminar «{0}»?",
        ["editor.importfail.title"] = "Error al importar",
        ["editor.importfail.body"] = "Ese archivo no es un .provisio-kit válido.",

        ["editor.hint.none"] = "Esta opción no instala nada. Úsala para preguntas de ramificación sí/no.",
        ["editor.hint.winget"] = "Destino = id de paquete winget, p. ej. Microsoft.PowerToys. Usa el campo de fuente para paquetes de la Store.",
        ["editor.hint.download"] = "Destino = URL de descarga directa. Formatos admitidos: .exe, .msi, .msix, .msixbundle, .appx, .appxbundle. Los paquetes MSIX/APPX se detectan solos y se instalan con Add-AppxPackage; los .exe/.msi se ejecutan con los argumentos silenciosos de abajo.",
        ["editor.hint.msix"] = "Destino = URL directa a un paquete MSIX (.msix, .msixbundle, .appx, .appxbundle). Se descarga y se instala con Add-AppxPackage. También admite una ruta local.",
        ["editor.hint.shell"] = "Destino = una línea de comandos ejecutada con cmd.exe, p. ej. npm install -g @anthropic-ai/claude-code. Útil para gestores de paquetes (npm, pip, uv, scoop, choco) y tareas de configuración.",
        ["editor.hint.script"] = "Destino = el cuerpo de un script de PowerShell. Marca «Requiere administrador» para todo lo que toque HKLM o ajustes del sistema.",
        ["editor.args.download"] = "Argumentos silenciosos (p. ej. /S o /quiet)",
        ["editor.args.shell"] = "Argumentos adicionales (se añaden al comando)",
        ["editor.target.winget"] = "Id de paquete",
        ["editor.target.download"] = "URL de descarga",
        ["editor.target.msix"] = "URL o ruta del paquete MSIX",
        ["editor.target.shell"] = "Comando de shell",
        ["editor.target.script"] = "Script de PowerShell",

        ["settings.title"] = "Ajustes",
        ["settings.appearance"] = "Apariencia",
        ["settings.appearance.desc"] = "El tema se aplica de inmediato a toda la aplicación.",
        ["settings.theme"] = "Tema",
        ["settings.theme.system"] = "Usar la configuración del sistema",
        ["settings.theme.light"] = "Claro",
        ["settings.theme.dark"] = "Oscuro",
        ["settings.language"] = "Idioma",
        ["settings.language.desc"] = "Idioma de la interfaz de Provisio. Los nombres y descripciones de los kits vienen de los archivos de kit y no se traducen.",
        ["settings.language.label"] = "Idioma de la interfaz",
        ["settings.packages"] = "Actualizaciones de paquetes",
        ["settings.packages.desc"] = "Provisio puede detectar versiones nuevas del software instalado en este PC (mediante winget) y actualizarlo por ti.",
        ["settings.packages.check"] = "Buscar actualizaciones de paquetes al iniciar Provisio",
        ["settings.packages.auto"] = "Instalar automáticamente las actualizaciones disponibles en segundo plano",
        ["settings.packages.open"] = "Abrir la página de actualizaciones",
        ["settings.appupdates"] = "Actualizaciones de Provisio",
        ["settings.appupdates.desc"] = "URL de un feed de actualización (JSON con appVersion, downloadUrl y definiciones de kit opcionales). Se comprueba al iniciar.",
        ["settings.checknow"] = "Comprobar ahora",
        ["settings.version"] = "Provisio {0}",
        ["settings.offline"] = "Modo sin conexión / portátil",
        ["settings.cache"] = "Guardar los instaladores descargados para reutilizarlos",
        ["settings.cachepath"] = "Caché de instaladores: {0}",
        ["settings.data"] = "Datos y primer inicio",
        ["settings.data.desc"] = "Los kits, perfiles, instaladores en caché y ajustes se guardan en tu carpeta local de datos.",
        ["settings.data.open"] = "Abrir carpeta de datos",
        ["settings.data.clearcache"] = "Vaciar caché de instaladores",
        ["settings.data.resetpopups"] = "Volver a mostrar los avisos de primer inicio",
        ["settings.data.cleared"] = "Caché de instaladores vaciada.",
        ["settings.data.reset"] = "Los avisos de bienvenida e importación se mostrarán de nuevo.",
        ["settings.about"] = "Acerca de",
        ["settings.about.body"] = "Provisio — un asistente de configuración inicial para Windows. Kits, perfiles y acciones propias se guardan como JSON legible para que puedas compartirlos e inspeccionarlos.",
        ["settings.updatecheck.title"] = "Comprobación de actualizaciones",
        ["settings.updatecheck.nourl"] = "No hay URL de feed configurada.",
        ["settings.updatecheck.found"] = "La versión {0} está disponible.",
        ["settings.updatecheck.none"] = "No se encontraron actualizaciones (o el feed no responde).",

        ["updates.title"] = "Actualizaciones de paquetes",
        ["updates.subtitle"] = "Software ya instalado en este PC con una versión más reciente disponible en winget.",
        ["updates.check"] = "Buscar actualizaciones",
        ["updates.checking"] = "Buscando actualizaciones…",
        ["updates.none"] = "Todo está actualizado.",
        ["updates.found"] = "{0} actualización(es) disponibles.",
        ["updates.updateselected"] = "Actualizar seleccionados",
        ["updates.updateall"] = "Actualizar todo",
        ["updates.col.package"] = "Paquete",
        ["updates.col.installed"] = "Instalada",
        ["updates.col.available"] = "Disponible",
        ["updates.running"] = "Actualizando {0}…",
        ["updates.finished"] = "Finalizado. {0} actualizados, {1} fallidos.",
        ["updates.nowinget"] = "No se encontró winget (App Installer) en este PC. Instala «App Installer» desde Microsoft Store para usar las actualizaciones.",
        ["updates.autorunning"] = "Instalando actualizaciones en segundo plano…",
        ["updates.notchecked"] = "Aún sin comprobar.",
        ["updates.available.bar"] = "{0} actualización(es) de paquetes disponibles.",
        ["updates.available.show"] = "Mostrar",

        ["rec.title"] = "Configuración recomendada",
        ["rec.subtitle"] = "Responde unas preguntas sobre cómo usas este PC. Provisio reunirá una lista curada de programas y ajustes de todos los kits — tú decides qué se añade.",
        ["rec.start"] = "Empezar cuestionario",
        ["rec.step"] = "Pregunta {0} de {1}",
        ["rec.multi"] = "Elige todo lo que aplique.",
        ["rec.single"] = "Elige una opción.",
        ["rec.finish"] = "Ver recomendaciones",
        ["rec.results.title"] = "Tu configuración recomendada",
        ["rec.results.subtitle"] = "{0} sugerencia(s) de {1} kit(s), según tus respuestas. Desmarca lo que no quieras y añade el resto.",
        ["rec.results.empty"] = "Tus respuestas no generaron recomendaciones. Repite el cuestionario con más opciones o explora los kits directamente.",
        ["rec.add"] = "Añadir a mi configuración",
        ["rec.restart"] = "Empezar de nuevo",
        ["rec.why"] = "Porque elegiste: {0}",
        ["rec.added.title"] = "Añadido a tu configuración",
        ["rec.added.body"] = "Se añadieron {0} elemento(s). Revísalos e inicia la instalación cuando quieras.",

        ["rec.q.use"] = "¿Para qué usas principalmente este PC?",
        ["rec.q.use.general"] = "Uso diario — navegar, correo, multimedia",
        ["rec.q.use.work"] = "Trabajo — documentos, reuniones, notas",
        ["rec.q.use.dev"] = "Desarrollo de software",
        ["rec.q.use.gaming"] = "Juegos",
        ["rec.q.level"] = "¿Cómo te describirías?",
        ["rec.q.level.beginner"] = "Principiante — quiero que funcione sin más",
        ["rec.q.level.confident"] = "Con experiencia — ajusto cosas de vez en cuando",
        ["rec.q.level.power"] = "Usuario avanzado — dame herramientas y atajos",
        ["rec.q.browser"] = "¿Qué navegador quieres?",
        ["rec.q.browser.chrome"] = "Google Chrome",
        ["rec.q.browser.firefox"] = "Mozilla Firefox",
        ["rec.q.browser.brave"] = "Algo centrado en la privacidad",
        ["rec.q.browser.keep"] = "Me quedo con el que ya tengo",
        ["rec.q.privacy"] = "¿Cuánto te importa la privacidad?",
        ["rec.q.privacy.default"] = "Los valores por defecto de Windows me valen",
        ["rec.q.privacy.some"] = "Desactivar rastreo y anuncios donde sea fácil",
        ["rec.q.privacy.max"] = "Reforzar todo — cifrado, VPN, cortafuegos",
        ["rec.q.ai"] = "¿Cómo quieres usar la IA?",
        ["rec.q.ai.none"] = "Nada",
        ["rec.q.ai.chat"] = "Aplicaciones de chat de escritorio",
        ["rec.q.ai.cli"] = "Agentes de código en la terminal",
        ["rec.q.ai.local"] = "Ejecutar modelos localmente en este PC",
        ["rec.q.dev"] = "¿Qué desarrollas?",
        ["rec.q.dev.none"] = "Nada / no aplica",
        ["rec.q.dev.web"] = "Web y JavaScript",
        ["rec.q.dev.python"] = "Python, datos o scripting",
        ["rec.q.dev.dotnet"] = "C# / .NET o aplicaciones de escritorio",
        ["rec.q.office"] = "¿Qué necesitas para documentos?",
        ["rec.q.office.none"] = "Nada especial",
        ["rec.q.office.free"] = "Una suite ofimática gratuita",
        ["rec.q.office.ms"] = "Microsoft Office / 365",
        ["rec.q.office.notes"] = "Notas y base de conocimiento",
        ["rec.q.gaming"] = "¿Cómo juegas?",
        ["rec.q.gaming.none"] = "No juego en este PC",
        ["rec.q.gaming.casual"] = "De vez en cuando, sobre todo Steam",
        ["rec.q.gaming.serious"] = "Mucho, en varias tiendas",
        ["rec.q.gaming.stream"] = "Grabo o transmito mis partidas",
        ["rec.q.creative"] = "¿Creas contenido multimedia?",
        ["rec.q.creative.none"] = "No",
        ["rec.q.creative.image"] = "Fotos y gráficos",
        ["rec.q.creative.video"] = "Vídeo y audio",
        ["rec.q.creative.3d"] = "3D y animación",
        ["rec.q.tweaks"] = "¿Debe Provisio ajustar el propio Windows?",
        ["rec.q.tweaks.none"] = "No, deja Windows como está",
        ["rec.q.tweaks.quality"] = "Sí — ajustes de comodidad",
        ["rec.q.tweaks.debloat"] = "Sí — y quitar el software preinstalado",
    };

    // ----------------------------------------------------------------- French

    private static Dictionary<string, string> Fr => new()
    {
        ["nav.kits"] = "Kits",
        ["nav.recommend"] = "Recommandé",
        ["nav.search"] = "Recherche",
        ["nav.profiles"] = "Profils",
        ["nav.editor"] = "Éditeur de kits",
        ["nav.updates"] = "Mises à jour",
        ["nav.settings"] = "Paramètres",

        ["common.back"] = "Retour",
        ["common.next"] = "Suivant",
        ["common.skip"] = "Passer cette étape",
        ["common.cancel"] = "Annuler",
        ["common.close"] = "Fermer",
        ["common.ok"] = "OK",
        ["common.save"] = "Enregistrer",
        ["common.delete"] = "Supprimer",
        ["common.import"] = "Importer",
        ["common.export"] = "Exporter",
        ["common.duplicate"] = "Dupliquer",
        ["common.done"] = "Terminé",
        ["common.retry"] = "Réessayer les échecs",
        ["common.yes"] = "Oui",
        ["common.no"] = "Non",
        ["common.continue"] = "Continuer",
        ["common.refresh"] = "Actualiser",
        ["common.selectall"] = "Tout sélectionner",
        ["common.clear"] = "Vider",
        ["common.updating"] = "Mise à jour…",
        ["common.failed"] = "Échec",
        ["status.queued"] = "En attente",
        ["status.downloading"] = "Téléchargement…",
        ["status.installing"] = "Installation…",
        ["status.skipped"] = "Ignoré",

        ["update.available"] = "Provisio {0} est disponible (vous avez {1}). {2}",
        ["update.download"] = "Télécharger",

        ["welcome.title"] = "Bienvenue dans Provisio",
        ["welcome.body"] = "Merci d'avoir téléchargé Provisio ! C'est un assistant de configuration pour Windows : choisissez vos kits, répondez à quelques questions, vérifiez le récapitulatif, et Provisio installe tout en une seule fois.\n\nRien n'est installé tant que vous n'avez pas confirmé sur l'écran de révision.",
        ["welcome.hint"] = "Astuce : vous ne savez pas par où commencer ? Essayez « Recommandé » — un court questionnaire qui compose la configuration pour vous.",
        ["welcome.start"] = "Parcourir les kits",
        ["welcome.recommend"] = "Lancer la configuration recommandée",

        ["security.title"] = "Avant d'importer un kit de la communauté",
        ["security.body"] = "Un kit n'est pas qu'une liste d'applications : il peut exécuter des commandes shell, des scripts PowerShell et des installateurs téléchargés avec votre compte — et, si le kit le demande, en tant qu'administrateur.\n\nN'importez que des kits provenant d'une source de confiance. Ouvrez d'abord le kit dans l'éditeur et lisez chaque action (id winget, URL de téléchargement, commande ou script) avant d'installer quoi que ce soit.",
        ["security.ack"] = "J'ai compris, continuer",
        ["security.info"] = "Cet avertissement n'est affiché qu'une fois. Les kits importés apparaissent toujours dans l'éditeur avant toute exécution.",

        ["kits.title"] = "Bienvenue dans Provisio",
        ["kits.subtitle"] = "Choisissez les kits à configurer. Rien n'est installé avant votre confirmation finale.",
        ["kits.review"] = "Vérifier la sélection",
        ["kits.start"] = "Démarrer la configuration",
        ["kits.none"] = "Aucun kit sélectionné",
        ["kits.count"] = "{0} kits sélectionnés",
        ["kits.count.one"] = "1 kit sélectionné",
        ["kits.nonetitle"] = "Aucun kit sélectionné",
        ["kits.nonebody"] = "Sélectionnez au moins un kit pour démarrer l'assistant.",

        ["wizard.kitof"] = "Kit {0} sur {1} — {2}",
        ["wizard.step"] = "Étape {0} sur {1}",
        ["wizard.review"] = "Révision",
        ["wizard.nextkit"] = "Kit suivant",

        ["summary.title"] = "Vérifiez votre configuration",
        ["summary.subtitle"] = "Tout ce qui est en file d'attente. Décochez ce que vous ne voulez pas — rien n'a encore été installé.",
        ["summary.saveprofile"] = "Enregistrer comme profil",
        ["summary.preview"] = "Voir les commandes",
        ["summary.install"] = "Installer",
        ["summary.empty"] = "Rien en attente. Revenez en arrière et choisissez des logiciels ou des réglages.",
        ["summary.previewtitle"] = "Simulation — commandes exactes qui seront exécutées",
        ["summary.nothingqueued"] = "Rien en attente.",
        ["summary.profiletitle"] = "Enregistrer la sélection comme profil",
        ["summary.profilename"] = "Nom du profil",

        ["install.title"] = "Installation",
        ["install.ready"] = "Prêt. L'installation se fait élément par élément ; un échec n'interrompt pas le reste.",
        ["install.nothing"] = "Rien en attente.",
        ["install.admin"] = "Certaines actions nécessitent des droits administrateur. Relancez Provisio en tant qu'administrateur.",
        ["install.restartadmin"] = "Relancer en administrateur",
        ["install.exportlog"] = "Exporter le journal",
        ["install.start"] = "Démarrer l'installation",
        ["install.restore.on"] = "Point de restauration : oui",
        ["install.restore.off"] = "Point de restauration : non",
        ["install.creatingrestore"] = "Création du point de restauration…",
        ["install.running"] = "Installation de {0}…",
        ["install.alldone"] = "Terminé.",
        ["install.failed"] = "Terminé avec {0} échec(s). Vous pouvez réessayer les éléments en échec.",

        ["search.title"] = "Tout rechercher",
        ["search.placeholder"] = "Trouver des applications et réglages dans tous les kits…",
        ["search.queue"] = "Ajouter",
        ["search.queued"] = "Ajouté",

        ["profiles.title"] = "Profils",
        ["profiles.subtitle"] = "Configurations enregistrées. Appliquez-en une pour restaurer toute la sélection multi-kits.",
        ["profiles.empty"] = "Aucun profil. Faites une sélection puis utilisez « Enregistrer comme profil » sur l'écran de révision.",
        ["profiles.apply"] = "Appliquer et vérifier",
        ["profiles.deletetitle"] = "Supprimer le profil ?",
        ["profiles.deletebody"] = "Supprimer « {0} » ?",
        ["profiles.items"] = "{0} élément(s) · enregistré {1}",

        ["editor.title"] = "Éditeur de kits",
        ["editor.newkit"] = "Nouveau kit",
        ["editor.kit"] = "Kit",
        ["editor.name"] = "Nom",
        ["editor.icon"] = "Icône (glyphe Segoe Fluent Icons)",
        ["editor.description"] = "Description",
        ["editor.pages"] = "Pages (étapes de l'assistant)",
        ["editor.addpage"] = "Ajouter une page",
        ["editor.removepage"] = "Supprimer la page",
        ["editor.selectedpage"] = "Page sélectionnée",
        ["editor.pageid"] = "Id de page (pour les branchements)",
        ["editor.question"] = "Question",
        ["editor.multiselect"] = "Autoriser plusieurs choix (désactivé = choix unique)",
        ["editor.condpage"] = "Afficher seulement si la page… (condition facultative)",
        ["editor.condchoice"] = "…a ce choix sélectionné (facultatif)",
        ["editor.choices"] = "Choix",
        ["editor.addchoice"] = "Ajouter un choix",
        ["editor.removechoice"] = "Supprimer le choix",
        ["editor.selectedchoice"] = "Choix sélectionné",
        ["editor.choiceid"] = "Id du choix",
        ["editor.action"] = "Action d'installation",
        ["editor.target"] = "Cible",
        ["editor.args"] = "Arguments",
        ["editor.source"] = "Source winget (facultatif : winget ou msstore)",
        ["editor.dependson"] = "Dépend de (ids de choix de ce kit, séparés par des virgules)",
        ["editor.admin"] = "Nécessite l'administrateur",
        ["editor.save"] = "Enregistrer le kit",
        ["editor.saved"] = "{0} enregistré ({1} pages).",
        ["editor.builtin"] = "Kit intégré — l'enregistrement crée votre propre copie modifiée.",
        ["editor.builtin.title"] = "Kit intégré",
        ["editor.builtin.body"] = "Les kits intégrés ne peuvent pas être supprimés. Dupliquez-le et modifiez la copie.",
        ["editor.deletetitle"] = "Supprimer le kit ?",
        ["editor.deletebody"] = "Supprimer « {0} » ?",
        ["editor.importfail.title"] = "Échec de l'import",
        ["editor.importfail.body"] = "Ce fichier n'est pas un .provisio-kit valide.",

        ["editor.hint.none"] = "Ce choix n'installe rien. Utilisez-le pour les questions de branchement oui/non.",
        ["editor.hint.winget"] = "Cible = id de paquet winget, par ex. Microsoft.PowerToys. Utilisez le champ source pour les paquets du Store.",
        ["editor.hint.download"] = "Cible = URL de téléchargement direct. Formats pris en charge : .exe, .msi, .msix, .msixbundle, .appx, .appxbundle. Les bundles MSIX/APPX sont détectés automatiquement et installés avec Add-AppxPackage ; les .exe/.msi sont lancés avec les arguments silencieux ci-dessous.",
        ["editor.hint.msix"] = "Cible = URL directe vers un bundle MSIX (.msix, .msixbundle, .appx, .appxbundle). Téléchargé puis installé avec Add-AppxPackage. Un chemin local fonctionne aussi.",
        ["editor.hint.shell"] = "Cible = une ligne de commande exécutée via cmd.exe, par ex. npm install -g @anthropic-ai/claude-code. Pratique pour les gestionnaires de paquets (npm, pip, uv, scoop, choco) et les tâches de configuration.",
        ["editor.hint.script"] = "Cible = le corps d'un script PowerShell. Cochez « Nécessite l'administrateur » pour tout ce qui touche HKLM ou les réglages système.",
        ["editor.args.download"] = "Arguments silencieux (par ex. /S ou /quiet)",
        ["editor.args.shell"] = "Arguments supplémentaires (ajoutés à la commande)",
        ["editor.target.winget"] = "Id de paquet",
        ["editor.target.download"] = "URL de téléchargement",
        ["editor.target.msix"] = "URL ou chemin du bundle MSIX",
        ["editor.target.shell"] = "Commande shell",
        ["editor.target.script"] = "Script PowerShell",

        ["settings.title"] = "Paramètres",
        ["settings.appearance"] = "Apparence",
        ["settings.appearance.desc"] = "Le thème s'applique immédiatement à toute l'application.",
        ["settings.theme"] = "Thème",
        ["settings.theme.system"] = "Suivre le système",
        ["settings.theme.light"] = "Clair",
        ["settings.theme.dark"] = "Sombre",
        ["settings.language"] = "Langue",
        ["settings.language.desc"] = "Langue de l'interface de Provisio. Les noms et descriptions des kits proviennent des fichiers de kit et ne sont pas traduits.",
        ["settings.language.label"] = "Langue de l'interface",
        ["settings.packages"] = "Mises à jour des paquets",
        ["settings.packages.desc"] = "Provisio peut détecter les nouvelles versions des logiciels installés sur ce PC (via winget) et les mettre à jour pour vous.",
        ["settings.packages.check"] = "Rechercher les mises à jour au démarrage de Provisio",
        ["settings.packages.auto"] = "Installer automatiquement les mises à jour disponibles en arrière-plan",
        ["settings.packages.open"] = "Ouvrir la page des mises à jour",
        ["settings.appupdates"] = "Mises à jour de Provisio",
        ["settings.appupdates.desc"] = "URL d'un flux de mise à jour (JSON avec appVersion, downloadUrl et définitions de kits facultatives). Vérifié au démarrage.",
        ["settings.checknow"] = "Vérifier maintenant",
        ["settings.version"] = "Provisio {0}",
        ["settings.offline"] = "Mode hors ligne / portable",
        ["settings.cache"] = "Conserver les installateurs téléchargés pour les réutiliser",
        ["settings.cachepath"] = "Cache des installateurs : {0}",
        ["settings.data"] = "Données et premier démarrage",
        ["settings.data.desc"] = "Kits, profils, installateurs en cache et paramètres sont stockés dans votre dossier de données local.",
        ["settings.data.open"] = "Ouvrir le dossier de données",
        ["settings.data.clearcache"] = "Vider le cache des installateurs",
        ["settings.data.resetpopups"] = "Réafficher les fenêtres de premier démarrage",
        ["settings.data.cleared"] = "Cache des installateurs vidé.",
        ["settings.data.reset"] = "Les fenêtres de bienvenue et d'avertissement seront réaffichées.",
        ["settings.about"] = "À propos",
        ["settings.about.body"] = "Provisio — un assistant de configuration pour Windows. Kits, profils et actions personnalisées sont stockés en JSON lisible, pour que vous puissiez les partager et les inspecter.",
        ["settings.updatecheck.title"] = "Vérification des mises à jour",
        ["settings.updatecheck.nourl"] = "Aucune URL de flux configurée.",
        ["settings.updatecheck.found"] = "La version {0} est disponible.",
        ["settings.updatecheck.none"] = "Aucune mise à jour trouvée (ou flux injoignable).",

        ["updates.title"] = "Mises à jour des paquets",
        ["updates.subtitle"] = "Logiciels déjà installés sur ce PC pour lesquels winget propose une version plus récente.",
        ["updates.check"] = "Rechercher les mises à jour",
        ["updates.checking"] = "Recherche des mises à jour…",
        ["updates.none"] = "Tout est à jour.",
        ["updates.found"] = "{0} mise(s) à jour disponible(s).",
        ["updates.updateselected"] = "Mettre à jour la sélection",
        ["updates.updateall"] = "Tout mettre à jour",
        ["updates.col.package"] = "Paquet",
        ["updates.col.installed"] = "Installée",
        ["updates.col.available"] = "Disponible",
        ["updates.running"] = "Mise à jour de {0}…",
        ["updates.finished"] = "Terminé. {0} mis à jour, {1} en échec.",
        ["updates.nowinget"] = "winget (App Installer) est introuvable sur ce PC. Installez « App Installer » depuis le Microsoft Store pour utiliser les mises à jour.",
        ["updates.autorunning"] = "Installation des mises à jour en arrière-plan…",
        ["updates.notchecked"] = "Pas encore vérifié.",
        ["updates.available.bar"] = "{0} mise(s) à jour de paquets disponible(s).",
        ["updates.available.show"] = "Afficher",

        ["rec.title"] = "Configuration recommandée",
        ["rec.subtitle"] = "Répondez à quelques questions sur votre usage de ce PC. Provisio compose ensuite une liste organisée de logiciels et de réglages issus de tous les kits — vous décidez ce qui est réellement ajouté.",
        ["rec.start"] = "Démarrer le questionnaire",
        ["rec.step"] = "Question {0} sur {1}",
        ["rec.multi"] = "Choisissez tout ce qui s'applique.",
        ["rec.single"] = "Choisissez une option.",
        ["rec.finish"] = "Voir les recommandations",
        ["rec.results.title"] = "Votre configuration recommandée",
        ["rec.results.subtitle"] = "{0} suggestion(s) issues de {1} kit(s), d'après vos réponses. Décochez ce que vous ne voulez pas, puis ajoutez le reste.",
        ["rec.results.empty"] = "Vos réponses n'ont produit aucune recommandation. Refaites le questionnaire avec plus d'options, ou parcourez les kits directement.",
        ["rec.add"] = "Ajouter à ma configuration",
        ["rec.restart"] = "Recommencer",
        ["rec.why"] = "Parce que vous avez choisi : {0}",
        ["rec.added.title"] = "Ajouté à votre configuration",
        ["rec.added.body"] = "{0} élément(s) ajoutés. Vérifiez-les et lancez l'installation quand vous voulez.",

        ["rec.q.use"] = "À quoi sert principalement ce PC ?",
        ["rec.q.use.general"] = "Usage quotidien — web, mail, médias",
        ["rec.q.use.work"] = "Travail — documents, réunions, notes",
        ["rec.q.use.dev"] = "Développement logiciel",
        ["rec.q.use.gaming"] = "Jeux",
        ["rec.q.level"] = "Comment vous décririez-vous ?",
        ["rec.q.level.beginner"] = "Débutant — je veux que ça marche, point",
        ["rec.q.level.confident"] = "À l'aise — je bidouille de temps en temps",
        ["rec.q.level.power"] = "Utilisateur avancé — donnez-moi les outils",
        ["rec.q.browser"] = "Quel navigateur voulez-vous ?",
        ["rec.q.browser.chrome"] = "Google Chrome",
        ["rec.q.browser.firefox"] = "Mozilla Firefox",
        ["rec.q.browser.brave"] = "Quelque chose axé sur la vie privée",
        ["rec.q.browser.keep"] = "Je garde celui déjà installé",
        ["rec.q.privacy"] = "Quelle importance accordez-vous à la vie privée ?",
        ["rec.q.privacy.default"] = "Les réglages Windows par défaut me conviennent",
        ["rec.q.privacy.some"] = "Désactiver le suivi et la pub quand c'est simple",
        ["rec.q.privacy.max"] = "Tout durcir — chiffrement, VPN, pare-feu",
        ["rec.q.ai"] = "Comment voulez-vous utiliser l'IA ?",
        ["rec.q.ai.none"] = "Pas du tout",
        ["rec.q.ai.chat"] = "Applications de chat de bureau",
        ["rec.q.ai.cli"] = "Agents de code dans le terminal",
        ["rec.q.ai.local"] = "Exécuter des modèles localement",
        ["rec.q.dev"] = "Que développez-vous ?",
        ["rec.q.dev.none"] = "Rien / sans objet",
        ["rec.q.dev.web"] = "Web et JavaScript",
        ["rec.q.dev.python"] = "Python, données ou scripts",
        ["rec.q.dev.dotnet"] = "C# / .NET ou applications de bureau",
        ["rec.q.office"] = "De quoi avez-vous besoin pour les documents ?",
        ["rec.q.office.none"] = "Rien de particulier",
        ["rec.q.office.free"] = "Une suite bureautique gratuite",
        ["rec.q.office.ms"] = "Microsoft Office / 365",
        ["rec.q.office.notes"] = "Notes et base de connaissances",
        ["rec.q.gaming"] = "Comment jouez-vous ?",
        ["rec.q.gaming.none"] = "Je ne joue pas sur ce PC",
        ["rec.q.gaming.casual"] = "Occasionnellement, surtout Steam",
        ["rec.q.gaming.serious"] = "Beaucoup, sur plusieurs plateformes",
        ["rec.q.gaming.stream"] = "J'enregistre ou je diffuse mes parties",
        ["rec.q.creative"] = "Créez-vous des médias ?",
        ["rec.q.creative.none"] = "Non",
        ["rec.q.creative.image"] = "Photos et graphisme",
        ["rec.q.creative.video"] = "Vidéo et audio",
        ["rec.q.creative.3d"] = "3D et animation",
        ["rec.q.tweaks"] = "Provisio doit-il ajuster Windows lui-même ?",
        ["rec.q.tweaks.none"] = "Non, ne touchez pas à Windows",
        ["rec.q.tweaks.quality"] = "Oui — réglages de confort",
        ["rec.q.tweaks.debloat"] = "Oui — et supprimer les logiciels préinstallés",
    };
}
